language: rust
sudo: 9000
dist: trusty
rust:
  - nightly
os:
  - linux
  - osx

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

script:
  - travis_wait cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
