language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

env:
  - FEATURES=""
  - FEATURES="debugmozjs"

before_script:
  - export PATH=$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH
  - pip install servo_tidy --user `whoami`

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
  - servo-tidy

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
