[package]

name = "js"
version = "0.1.2"
authors = ["The Servo Project Developers"]

build = "build.rs"

[[test]]
name = "callback"
[[test]]
name = "evaluate"
[[test]]
name = "stack_limit"
[[test]]
name = "vec_conversion"

[lib]
doctest = false

[features]
debugmozjs = ['mozjs_sys/debugmozjs']

[dependencies.mozjs_sys]
git = "https://github.com/servo/mozjs"
branch = "smup"

[dependencies]
libc = "0.2"
rustc-serialize = "0.3"
log = "0.3"
heapsize = ">=0.2, <0.4"
num = "0.1.24"
